### ISSUE TITLE
[Known] POSSE to Twitter not working

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/indiehosters-docker-bash#3]
This is due to https://github.com/idno/idno/issues/608

I'll see if I can help them fix it for 0.6.6

**Comment by michielbdejong** [comment]
fixed by setting the url explicitly in config.ini

**Comment by pierreozoux** [comment]
hey, how do you set up the url in config.ini?

Danke!

**Comment by michielbdejong** [comment]
This is the config I use (there is a MySQL instance running inside the lamp-git container of this repo):

```
root@l1:~# cat /data/domains/michielbdejong.com/www-content/config.ini 
database = 'MySQL'
dbhost = 'localhost'
dbname = 'known'
dbuser = 'root'
dbpass = ''
filesystem = 'local'
uploadpath = '/data/uploads/'
url = 'https://michielbdejong.com/'
root@l1:~# 
```

**Comment by pierreozoux** [comment]
ok, thanks, but I still have an issue of mixed content...

**Comment by pierreozoux** [comment]
I didn't find anything on the documentation regarding this variable, could point me to it please? danke!

**Comment by michielbdejong** [comment]
I think I found it by browsing the Idno code, https://github.com/idno/Known/issues/724 mentions the detectBaseURL function.
